######################################
#       START SECTION 0              #
#       BASIC DEPENDENCIES           #
######################################
FROM ubuntu:20.04

RUN apt-get clean -y
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install wget gnupg curl unzip jq apt-transport-https dos2unix nano zip python3 python3-pip -y
RUN apt-get update -y
RUN apt-get upgrade -y

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
RUN apt-get install -y software-properties-common

######################################
#       START SECTION                #
#       Install Powershell           #
######################################

RUN wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y powershell

######################################
#       START SECTION 3              #
#       ADD TO PATH                  #
######################################
ENV PATH="/bin:${PATH}"

######################################
#       START SECTION 4              #
#       COPY DEPLOY CODES            #
######################################
COPY . /app

######################################
#       START SECTION 5              #
#       dos2Unix Everything          #
######################################
RUN find /app/deploy -type f -print0 | xargs -0 -n 1 -P 4 dos2unix

######################################
#       START SECTION 6              #
#       EVERYTHING +x                #
######################################
RUN chmod -x -R /app/*

######################################
#                                    #
#      INSTALL APP DEPENDENCIES      #
#                                    #
######################################
RUN pip3 install -r /app/requirements.txt


######################################
#       START SECTION 7              #
#       RUN COMMAND                  #
######################################
WORKDIR /app/
CMD ["pwsh", "./bootloader.ps1"]